### PR TITLE
Add luacheck action and fix linting warnings

### PR DESCRIPTION
**Pull request by Omikhleia**
Greetings,
This PR is a proposal
- fixing several linting warnings or errors
- adding a GitHub action (= CI pipeline) to the repository, so that to ensure linting checks are performed automatically when changed are pushed.

I fixed here the most "obvious" warnings/errors, ensured `qrtest.lua` still reported no error, and also checked a few QR codes I had previously generated with `qrcode.lua` were unchanged.

_As of this initial PR_, though, I have left **two warnings unaddressed** (in the same portion of code): I am unsure what the loop there does exactly and whether this might hint toward some small logic error possibly - So I preferred not silencing them. Please feel free to check and comment.

(for that reason, I haven't proposed adding a Luacheck badge to the README, since it still fails for now)

### CODE REVIEW

**Comment by Omikhleia** [comment]
I could have added a link to the above-mentioned unaddressed lint warnings:
https://github.com/Omikhleia/luaqrcode/actions/runs/3664504028/jobs/6194957626

**Comment by pgundlach** [comment]
Thank you very much. I will take a look at it and report back.

**Review by alerque — APPROVED** [review]

**Review by pgundlach — APPROVED** [review]
The changes look good to me.

**Comment by pgundlach** [comment]
I hope I have merged this correctly. I am not an expert using GitHub and its actions. Thank you very much for your work!

**Pull request merged**
